test

diff --git a/.github/workflows/ec2-docker-cd.yml b/.github/workflows/ec2-docker-cd.yml
--- a/.github/workflows/ec2-docker-cd.yml
+++ b/.github/workflows/ec2-docker-cd.yml
@@ -46,13 +46,23 @@ jobs:
 
           # EC2에 접속하여 기존 컨테이너 중지 및 새 도커 이미지 실행
           ssh -i ec2_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
+            # Install Docker if not installed
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+              sudo amazon-linux-extras install docker -y
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              sudo usermod -aG docker $USER
+            fi
+            
             # 기존 컨테이너 중지 및 삭제
-            docker stop myapp || true
-            docker rm myapp || true
+            docker stop iris-inference || true
+            docker rm iris-inference || true
 
             # Docker Hub에서 최신 이미지 가져오기
-            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
+            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/iris-inference:latest
 
             # 새 이미지를 기반으로 컨테이너 실행
-            docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
+            docker run -d --name iris-inference -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/iris-inference:latest
           EOF
